"""
Owner authentication for the control plane.

The whole product rests on one principle: a held action is released only by the
human who owns the home, through a channel the AI cannot drive. Sensitive endpoints
(resolving approvals, changing policies, revoking agents) require a valid owner
session. The model has no way to present one.

Auth flow:
  POST /auth/login   — submit the owner passphrase (ORA_OWNER_TOKEN env var);
                       server sets an HttpOnly session cookie.
  require_owner dep  — reads the cookie and validates it via the sessions table.
  POST /auth/logout  — revokes the session and clears the cookie.

The passphrase is read from ORA_OWNER_TOKEN (generated by setup.ps1 / setup.sh
on first run and printed to the server log). On initial startup without the env
var set, a token is generated and written to oracle_keys/owner.token.

SameSite=Strict note:
  Strict prevents the cookie from riding along on top-level navigations from a
  foreign origin — correct for a directly-visited SPA. When push-approvals (#6)
  ships, deep-link click-throughs from Telegram will land with no cookie, causing
  a 401 on the first request. At that point, consider SameSite=Lax on the
  /approvals/* path (or use a short-lived URL token for the click-through).
  Flag raised here so the behaviour isn't discovered in prod.

Secure flag note:
  secure= is set only when ORA_HTTPS is explicitly set to "1", "true", or "yes".
  bool(os.getenv("ORA_HTTPS")) would treat the string "0" as True — set it
  explicitly to avoid silently breaking cookies over plain HTTP.
"""
import hmac
import os

from fastapi import Cookie, HTTPException

import crypto
import sessions

# ── Passphrase resolution ──────────────────────────────────────────────────────

_DATA_DIR   = os.environ.get("ORA_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))
TOKEN_FILE  = os.path.join(_DATA_DIR, "oracle_keys", "owner.token")
_passphrase: str | None = None


def owner_token() -> str:
    """Return the owner passphrase, generating and persisting it on first call."""
    global _passphrase
    if _passphrase is not None:
        return _passphrase

    env = os.getenv("ORA_OWNER_TOKEN")
    if env:
        _passphrase = env.strip()
        return _passphrase

    os.makedirs(os.path.dirname(TOKEN_FILE), exist_ok=True)
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE) as f:
            _passphrase = f.read().strip()
    else:
        _passphrase = crypto.new_token()
        with open(TOKEN_FILE, "w") as f:
            f.write(_passphrase)
        try:
            os.chmod(TOKEN_FILE, 0o600)
        except OSError:
            pass
        print("\n" + "=" * 64)
        print("  Ora owner passphrase (use at the login screen):")
        print(f"  {_passphrase}")
        print("  Set ORA_OWNER_TOKEN to this value to persist it across restarts.")
        print("=" * 64 + "\n")
    return _passphrase


def verify_passphrase(submitted: str) -> bool:
    """Constant-time comparison against the owner passphrase."""
    if not submitted:
        return False
    return hmac.compare_digest(submitted.strip(), owner_token())


# ── Session cookie helper ─────────────────────────────────────────────────────

# Fix: explicit string check so ORA_HTTPS=0 doesn't accidentally set Secure.
# bool("0") is True in Python — the string "0" is a truthy non-empty string.
HTTPS = os.getenv("ORA_HTTPS", "").lower() in ("1", "true", "yes")


# ── FastAPI dependency ─────────────────────────────────────────────────────────

def require_owner(
    session: str | None = Cookie(default=None, alias="ora_session"),
) -> bool:
    """Validate the HttpOnly session cookie. Used as a FastAPI dependency.

    The seam is isolated here so replacing session auth with OAuth or any
    other scheme means changing only this function and the login/logout routes.
    """
    if not sessions.validate(session):
        raise HTTPException(status_code=401, detail="Owner session required.")
    return True
